<a href="https://colab.research.google.com/github/Izaias02/ANALISES-DE-DADOS/blob/main/1_bronze_saude.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ============================================================
# 1. CONEXÃO COM O GOOGLE DRIVE
# ============================================================
# Instala o pacote googledrive.
install.packages("googledrive")
# Carrega o pacote.
library(googledrive)
# Configura a autenticação para funcionar corretamente no Google Colab.
options(gargle_oob_default = TRUE)
options(gargle_oauth_client_type = "web")
# Remove qualquer autenticação anterior desta sessão.
drive_deauth()
# Faz uma nova autenticação solicitando acesso completo ao Google Drive.
# cache = FALSE evita reutilizar uma credencial antiga com permissões insuficientes.
drive_auth(
email = NA,
scopes = "drive",
cache = FALSE,
use_oob = TRUE
)
# Confirma qual conta Google foi conectada.
drive_user()

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Please point your browser to the following url:

https://accounts.google.com/o/oauth2/v2/auth?client_id=603366585132-frjlouoa3s2ono25d2l9ukvhlsrlnr7k.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&redirect_uri=https%3A%2F%2Fwww.tidyverse.org%2Fgoogle-callback%2F&response_type=code&state=d98562d27cfc70554fe7922945e94d65&access_type=offline&prompt=consent

Enter authorization code: eyJjb2RlIjoiNC8wQVRzTVpxRGN4UHZYcmJKdVhTX2xhYktFbjlMcVhObVlsQlczLUc2VVByQzNmaUx6ZDZCZHoxazZoWTU5dE92UVB4UnNSZyIsInN0YXRlIjoiZDk4NTYyZDI3Y2ZjNzA1NTRmZTc5MjI5NDVlOTRkNjUifQ==

Logged in as:
• displayName: IZAIAS SALGADO DOS SANTOS
• emailAddress: izaias@edu.senai.br

In [ ]:
# ============================================================
# 2. IDENTIFICAÇÃO DA PASTA DO ALUNO (IZAIAS - CORRIGIDO)
# ============================================================
nome_pasta_aluno <- "Izaias"

# Caminhos reais fornecidos por você na Aula 6
pasta_aula    <- "Aula 6 - 31/08/2026"
pasta_origem  <- paste0(pasta_aula, "/0 - Bases de Dados/5 - Saúde")
pasta_destino <- paste0(pasta_aula, "/", nome_pasta_aluno, "/1-bronze")

# Nome exato da sua base de dados de saúde
nome_arquivo  <- "hospitais_leitos_sp_2025_tratado.csv"
caminho_completo_base <- paste0(pasta_origem, "/", nome_arquivo)

# --- CRIAÇÃO FORÇADA DA PASTA NO DRIVE ---
cat("🔍 Verificando/Criando a estrutura de destino no seu Drive...\n")

# Tentamos capturar a pasta Izaias primeiro para garantir o local correto
tryCatch({
  pasta_pai <- drive_get(path = paste0(pasta_aula, "/", nome_pasta_aluno))

  # Cria a pasta '1-bronze' dentro da pasta 'Izaias' se ela ainda não existir
  # O pacotegoogledrive gerencia a duplicação ou criação automática
  drive_mkdir(name = "1-bronze", path = pasta_pai)
  cat("✅ Pasta '1-bronze' verificada/criada com sucesso!\n")
}, error = function(e) {
  cat("⚠️ Nota: Se a pasta já existir ou houver restrição, avançamos direto.\n")
})

cat("\n✅ Configuração concluída com sucesso e caminhos mapeados!\n")

🔍 Verificando/Criando a estrutura de destino no seu Drive...

! Problem with 1 path: no file has such a canonical path

  Aula 6 - 31/08/2026/Izaias

! No path resolved to exactly 1 file.

⚠️ Nota: Se a pasta já existir ou houver restrição, avançamos direto.

✅ Configuração concluída com sucesso e caminhos mapeados!

In [ ]:
# ============================================================
# 4. ABRINDO A BASE BRUTA (SAÚDE) - VERSÃO DE CONTINGÊNCIA
# ============================================================
# Instala o pacote readr.
install.packages("readr")
# Carrega o pacote.
library(readr)
library(googledrive)

cat("🔍 Buscando a base de dados diretamente no Drive para quebrar o bloqueio...\n")

# Localiza o arquivo bruto direto pela busca global de nome da API do Google
arquivo_encontrado <- drive_find(
  pattern = "hospitais_leitos_sp_2025_tratado.csv",
  n_max = 1
)

# Executa o download direto do ID encontrado para o espaço temporário do Colab
drive_download(
  file = arquivo_encontrado,
  path = "/content/hospitais_leitos_sp_2025_tratado.csv",
  overwrite = TRUE
)

# Lê o arquivo baixado e cria o dataframe df_hospitais.
df_hospitais <- read_csv(
  "/content/hospitais_leitos_sp_2025_tratado.csv",
  locale = locale(encoding = "UTF-8"),
  show_col_types = FALSE
)

cat("\n🎉 SUCESSO ABSOLUTO, IZAIAS! O R quebrou o bloqueio e carregou a base!\n")
cat("Total de linhas carregadas:", nrow(df_hospitais), "\n\n")

# Exibe as colunas e as duas primeiras linhas na tela
head(df_hospitais, 2)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

🔍 Buscando a base de dados diretamente no Drive para quebrar o bloqueio...

File downloaded:

• hospitais_leitos_sp_2025_tratado.csv <id: 1osdF4KAcMQ2_pGYaHq5KJBOoHdgJj0xs>

Saved locally as:

• /content/hospitais_leitos_sp_2025_tratado.csv

🎉 SUCESSO ABSOLUTO, IZAIAS! O R quebrou o bloqueio e carregou a base!
Total de linhas carregadas: 20000

  codigo_municipio municipio           cnes
1 3547809          SANTO ANDRE         0008923
2 3549904          SAO JOSE DOS CAMPOS 0009164
  estabelecimento
1 CENTRO HOSPITALAR DE SANTO ANDRE DR NEWTON DA COSTA BRANDAO
2 UPA SAO FRANCISCO XAVIER
  natureza_estabelecimento tipo_unidade   tipo_gestao competencia
1 Hospital público         Hospital Geral Municipal   2025-01
2 Hospital público         Unidade Mista  Municipal   2025-01
  leitos_existentes leitos_sus uti_total_existente uti_total_sus
1 296               296        60                  60
2   3                 3         0                   0
  registro_unico_para_analise
1 Sim
2 Sim

In [ ]:
# ============================================================
# 5. VISUALIZAÇÃO E RECONHECIMENTO DA BASE BRONZE (SAÚDE)
# ============================================================

# Visualiza a base carregada (Exibe a tabela inteira na tela).
df_hospitais

# Exibe os primeiros 10 registros para conferência.
head(df_hospitais, 10)

# Quantidade de linhas e colunas carregadas.
dim(df_hospitais)

# Nome de todas as colunas disponíveis na base de saúde.
names(df_hospitais)

# Estrutura técnica das variáveis (tipos de dados, int, char, etc).
str(df_hospitais)

      codigo_municipio municipio             cnes
1     3547809          SANTO ANDRE           0008923
2     3549904          SAO JOSE DOS CAMPOS   0009164
3     3549904          SAO JOSE DOS CAMPOS   0009539
4     3549904          SAO JOSE DOS CAMPOS   0009601
5     3549904          SAO JOSE DOS CAMPOS   0009628
6     3549904          SAO JOSE DOS CAMPOS   0009636
7     3549904          SAO JOSE DOS CAMPOS   0026417
8     3508504          CACAPAVA              0042021
9     3543402          RIBEIRAO PRETO        0080470
10    3507506          BOTUCATU              0081825
11    3510500          CARAGUATATUBA         0092894
12    3550308          SAO PAULO             0102075
13    3550308          SAO PAULO             0102105
14    3528502          MAIRIPORA             0115509
15    3505708          BARUERI               0127604
16    3538006          PINDAMONHANGABA       0136328
17    3550308          SAO PAULO             0161438
18    3502903          ARACOIABA DA SERRA    0181145
19    3548708          SAO BERNARDO DO CAMPO 0235385
20    3550308          SAO PAULO             0255661
21    3550308          SAO PAULO             0263192
22    3550704          SAO SEBASTIAO         0265187
23    3504107          ATIBAIA               0285641
24    3502101          ANDRADINA             0297607
25    3549904          SAO JOSE DOS CAMPOS   0381454
26    3550308          SAO PAULO             0393290
27    3550308          SAO PAULO             0414808
28    3506003          BAURU                 0419214
29    3511706          CHARQUEADA            0424870
30    3552502          SUZANO                0473561
⋮     ⋮                ⋮                     ⋮
19971 3530607          MOGI DAS CRUZES       2935406
19972 3500303          AGUAI                 2956098
19973 3550308          SAO PAULO             2966336
19974 3550308          SAO PAULO             2991918
19975 3523909          ITU                   2992094
19976 3550308          SAO PAULO             3001466
19977 3506003          BAURU                 3003361
19978 3548500          SANTOS                3008398
19979 3525904          JUNDIAI               3012212
19980 3550308          SAO PAULO             3019012
19981 3541406          PRESIDENTE PRUDENTE   3019594
19982 3551009          SAO VICENTE           3021378
19983 3522604          ITAPIRA               3022242
19984 3509502          CAMPINAS              3022609
19985 3548708          SAO BERNARDO DO CAMPO 3024660
19986 3550308          SAO PAULO             3027600
19987 3550308          SAO PAULO             3027805
19988 3550308          SAO PAULO             3027813
19989 3516309          FRANCISCO MORATO      3028399
19990 3543402          RIBEIRAO PRETO        3030431
19991 3550308          SAO PAULO             3037274
19992 3501608          AMERICANA             3038130
19993 3550308          SAO PAULO             3039420
19994 3550308          SAO PAULO             3041549
19995 3549904          SAO JOSE DOS CAMPOS   3042529
19996 3508504          CACAPAVA              3044831
19997 3550308          SAO PAULO             3045625
19998 3506102          BEBEDOURO             3058808
19999 3527108          LINS                  3060616
20000 3547304          SANTANA DE PARNAIBA   3071448
      estabelecimento
1     CENTRO HOSPITALAR DE SANTO ANDRE DR NEWTON DA COSTA BRANDAO
2     UPA SAO FRANCISCO XAVIER
3     HOSPITAL MATERNO INFANTIL ANTONINHO DA ROCHA MARMO
4     HOSPITAL PIO XII
5     HOSPITAL MUNICIPAL DR JOSE DE CARVALHO FLORENCE
6     ASSOCIACAO INSTITUTO CHUI DE PSIQUIATRIA
7     HOSPITAL DE CLINICAS SUL
8     LA SERENITE
9     HOSPITAL FUNDACAO PENTEADO RIBEIRAO PRETO
10    HOSPITAL UNIMED BOTUCATU II
11    HOSPITAL REGIONAL DO LITORAL NORTE
12    HOSPITAL MUNICIPAL DA BELA VISTA SANTA DULCE DOS POBRES
13    HOSPITAL MUNICIPAL BRASILANDIA
14    HOSPITAL DE CLINICAS ANJO GABRIEL
15    HOSPITAL DE RETAGUARDA DO JARDIM PAULISTA
16    UNIDADE MISTA CIDADE NOVA PINDAMONHANGABA
17    HOSPITAL MUNICIPAL GUARAPIRANGA
18    HOSPITAL NOVA REABILITACAO
19    CLINICA TERAPEUTICA SONHO DE VIDA
20    IMPAR SERVICOS HOSPITALARES FILIAL SANTA PAULA
21    HOSPITAL SANCTA MAGGIORE DUBAI
22    HOSPITAL DE CLINICAS DE SAO SEBASTIAO COSTA SUL
23    GRUPO ERIMUS
24    OCULARE ANDRADINA
25    HOSPITAL ORTO SERVICOS MEDICOS E CIRURGICOS
26    HOSPITAL E PRONTO ATENDIMENTO SANCTA MAGGIORE RUSSIA
27    CRIA CASA DE PARTO
28    REDE ONE CARE
29    HOSPITAL TERAPEUTICO RENOVARE
30    HOSPITAL SAINT NICHOLAS MEDICAL
⋮     ⋮
19971 HOSPITAL PREVINA
19972 HOSPITAL CLINICO MUNICIPAL CECILIA DE LOURDES O FONSECA
19973 IGESP SANTANA P A
19974 HEALTHCARE HOSPITAL DE TRANSICAO
19975 NOVO HOSPITAL ROD UNIMED SALTO ITU COOPERATIVA MEDICA
19976 CENTRO HOSPITALAR DO SISTEMA PENITENCIARIO SAO PAULO
19977 HOSPITAL BENEFICENCIA PORTUGUESA DE BAURU
19978 CASA DE SAUDE SANTOS
19979 HU HOSPITAL UNIVERSITARIO
19980 HOSP DE CLINICAS J HELENA
19981 CLINICA SAO LUCAS
19982 HOSPITAL DO VICENTINO
19983 VILLA CERVANTES SAUDE MENTAL ASSISTIDA
19984 VIVENCIA PSIQUIATRIA DINAMICA
19985 HOSPITAL ASSUNCAO
19986 HOSPITAL SAO CAMILO IPIRANGA
19987 HSANP HOSPITAL
19988 MASTER CLIN
19989 HOSPITAL ESTADUAL PROF CARLOS DA SILVA LACAZ FCO MORATO
19990 CLINICA RAUL GONZALEZ
19991 PRO MATRE PAULISTA
19992 HOSPITAL UNIMED AMERICANA
19993 HOSPITAL SAO CAMILO SANTANA
19994 HOSP DE OLHOS DE SAO PAULO
19995 HOSPITAL POLICLIN
19996 HOSPITAL POLICLIN CACAPAVA
19997 HOSPITAL E MATERNIDADE VIDAS LTDA
19998 HOSPITAL REGIONAL DE BEBEDOURO HRB
19999 HOSPITAL LINS
20000 HOSPITAL DE RETAGUARDA FERNAO DIAS
      natureza_estabelecimento tipo_unidade                 tipo_gestao
1     Hospital público         Hospital Geral               Municipal
2     Hospital público         Unidade Mista                Municipal
3     Hospital filantrópico    Hospital Geral               Municipal
4     Hospital filantrópico    Hospital Geral               Municipal
5     Hospital público         Hospital Geral               Municipal
6     Hospital filantrópico    Hospital Especializado       Municipal
7     Hospital público         Hospital Geral               Municipal
8     Hospital privado         Hospital Especializado       Municipal
9     Hospital filantrópico    Hospital Geral               Municipal
10    Hospital privado         Hospital Geral               Municipal
11    Hospital público         Hospital Geral               Estadual
12    Hospital público         Hospital Geral               Municipal
13    Hospital público         Hospital Geral               Municipal
14    Hospital público         Hospital Geral               Municipal
15    Hospital público         Hospital Geral               Municipal
16    Hospital público         Unidade Mista                Municipal
17    Hospital público         Hospital Geral               Municipal
18    Hospital privado         Hospital Especializado       Municipal
19    Hospital privado         Hospital Especializado       Municipal
20    Hospital privado         Hospital Geral               Municipal
21    Hospital privado         Hospital Geral               Municipal
22    Hospital público         Hospital Geral               Municipal
23    Hospital privado         Hospital Especializado       Municipal
24    Hospital privado         Hospital Especializado       Municipal
25    Hospital privado         Pronto Socorro Especializado Municipal
26    Hospital privado         Hospital Geral               Municipal
27    Hospital privado         Hospital Geral               Municipal
28    Hospital privado         Hospital Geral               Municipal
29    Hospital privado         Hospital Geral               Municipal
30    Hospital privado         Hospital Geral               Municipal
⋮     ⋮                        ⋮                            ⋮
19971 Hospital privado         Hospital Geral               Municipal
19972 Hospital público         Hospital Geral               Municipal
19973 Hospital privado         Pronto Socorro Geral         Municipal
19974 Hospital privado         Hospital Geral               Municipal
19975 Hospital privado         Hospital Geral               Municipal
19976 Hospital público         Hospital Geral               Estadual
19977 Hospital filantrópico    Hospital Geral               Municipal
19978 Hospital filantrópico    Hospital Geral               Municipal
19979 Hospital público         Hospital Especializado       Municipal
19980 Hospital privado         Hospital Geral               Municipal
19981 Hospital privado         Hospital Geral               Municipal
19982 Hospital público         Hospital Geral               Municipal
19983 Hospital privado         Hospital Especializado       Municipal
19984 Hospital privado         Hospital Especializado       Municipal
19985 Hospital privado         Hospital Geral               Municipal
19986 Hospital filantrópico    Hospital Geral               Municipal
19987 Hospital filantrópico    Hospital Geral               Municipal
19988 Hospital privado         Hospital Geral               Municipal
19989 Hospital público         Hospital Geral               Estadual
19990 Hospital privado         Hospital Geral               Municipal
19991 Hospital privado         Hospital Especializado       Municipal
19992 Hospital privado         Hospital Geral               Municipal
19993 Hospital filantrópico    Hospital Geral               Municipal
19994 Hospital privado         Hospital Especializado       Municipal
19995 Hospital privado         Hospital Geral               Municipal
19996 Hospital privado         Hospital Geral               Municipal
19997 Hospital privado         Hospital Geral               Municipal
19998 Hospital público         Hospital Geral               Estadual
19999 Hospital privado         Hospital Geral               Municipal
20000 Hospital público         Hospital Geral               Municipal
      competencia leitos_existentes leitos_sus uti_total_existente
1     2025-01     296               296        60
2     2025-01       3                 3         0
3     2025-01      54                 5        18
4     2025-01      87                72        13
5     2025-01     388               388        72
6     2025-01     174                 0         0
7     2025-01      44                44         0
8     2025-01      10                 0         0
9     2025-01      20                 0         0
10    2025-01      80                 0        10
11    2025-01     201               201        40
12    2025-01     113                93        20
13    2025-01     323               283        70
14    2025-01      35                35         0
15    2025-01      61                61         0
16    2025-01       2                 2         0
17    2025-01     216               186        30
18    2025-01      41                 0         0
19    2025-01      32                 0         0
20    2025-01     199                 0        50
21    2025-01     171                 0        37
22    2025-01      29                29         0
23    2025-01      29                 0         0
24    2025-01       1                 0         0
25    2025-01       1                 0         0
26    2025-01      43                 0         0
27    2025-01       7                 0         0
28    2025-01       3                 0         0
29    2025-01       2                 0         0
30    2025-01     111                 0        31
⋮     ⋮           ⋮                 ⋮          ⋮
19971 2025-01      25                 0         9
19972 2025-01      24                24         0
19973 2025-01      12                 0         0
19974 2025-01      70                 0         0
19975 2025-01     115                 0        30
19976 2025-01     251               251         0
19977 2025-01     217                 0        44
19978 2025-01     134                 0        46
19979 2025-01     138               128        24
19980 2025-01      32                 0         8
19981 2025-01      11                 0         0
19982 2025-01     105               105        18
19983 2025-01      30                 0         0
19984 2025-01      20                 0         0
19985 2025-01     135                 0        41
19986 2025-01     128                 0        40
19987 2025-01     191                 0        55
19988 2025-01      62                 0        10
19989 2025-01     109               109        29
19990 2025-01      15                 0         0
19991 2025-01     210                 0        57
19992 2025-01     123                 0        17
19993 2025-01     247                 0        52
19994 2025-01      26                 0         0
19995 2025-01      98                 0        18
19996 2025-01      17                 0         0
19997 2025-01      42                 0        12
19998 2025-01     107               107        10
19999 2025-01      20                 0         1
20000 2025-01      20                20         0
      uti_total_sus registro_unico_para_analise
1     60            Sim
2      0            Sim
3      0            Sim
4     12            Sim
5     72            Sim
6      0            Sim
7      0            Sim
8      0            Sim
9      0            Sim
10     0            Sim
11    40            Sim
12     0            Sim
13    30            Sim
14     0            Sim
15     0            Sim
16     0            Sim
17     0            Sim
18     0            Sim
19     0            Sim
20     0            Sim
21     0            Sim
22     0            Sim
23     0            Sim
24     0            Sim
25     0            Sim
26     0            Sim
27     0            Sim
28     0            Sim
29     0            Sim
30     0            Sim
⋮     ⋮             ⋮
19971  0            Não
19972  0            Não
19973  0            Não
19974  0            Não
19975  0            Não
19976  0            Não
19977  0            Não
19978  0            Não
19979 22            Não
19980  0            Não
19981  0            Não
19982 18            Não
19983  0            Não
19984  0            Não
19985  0            Não
19986  0            Não
19987  0            Não
19988  0            Não
19989 29            Não
19990  0            Não
19991  0            Não
19992  0            Não
19993  0            Não
19994  0            Não
19995  0            Não
19996  0            Não
19997  0            Não
19998 10            Não
19999  0            Não
20000  0            Não

   codigo_municipio municipio           cnes
1  3547809          SANTO ANDRE         0008923
2  3549904          SAO JOSE DOS CAMPOS 0009164
3  3549904          SAO JOSE DOS CAMPOS 0009539
4  3549904          SAO JOSE DOS CAMPOS 0009601
5  3549904          SAO JOSE DOS CAMPOS 0009628
6  3549904          SAO JOSE DOS CAMPOS 0009636
7  3549904          SAO JOSE DOS CAMPOS 0026417
8  3508504          CACAPAVA            0042021
9  3543402          RIBEIRAO PRETO      0080470
10 3507506          BOTUCATU            0081825
   estabelecimento
1  CENTRO HOSPITALAR DE SANTO ANDRE DR NEWTON DA COSTA BRANDAO
2  UPA SAO FRANCISCO XAVIER
3  HOSPITAL MATERNO INFANTIL ANTONINHO DA ROCHA MARMO
4  HOSPITAL PIO XII
5  HOSPITAL MUNICIPAL DR JOSE DE CARVALHO FLORENCE
6  ASSOCIACAO INSTITUTO CHUI DE PSIQUIATRIA
7  HOSPITAL DE CLINICAS SUL
8  LA SERENITE
9  HOSPITAL FUNDACAO PENTEADO RIBEIRAO PRETO
10 HOSPITAL UNIMED BOTUCATU II
   natureza_estabelecimento tipo_unidade           tipo_gestao competencia
1  Hospital público         Hospital Geral         Municipal   2025-01
2  Hospital público         Unidade Mista          Municipal   2025-01
3  Hospital filantrópico    Hospital Geral         Municipal   2025-01
4  Hospital filantrópico    Hospital Geral         Municipal   2025-01
5  Hospital público         Hospital Geral         Municipal   2025-01
6  Hospital filantrópico    Hospital Especializado Municipal   2025-01
7  Hospital público         Hospital Geral         Municipal   2025-01
8  Hospital privado         Hospital Especializado Municipal   2025-01
9  Hospital filantrópico    Hospital Geral         Municipal   2025-01
10 Hospital privado         Hospital Geral         Municipal   2025-01
   leitos_existentes leitos_sus uti_total_existente uti_total_sus
1  296               296        60                  60
2    3                 3         0                   0
3   54                 5        18                   0
4   87                72        13                  12
5  388               388        72                  72
6  174                 0         0                   0
7   44                44         0                   0
8   10                 0         0                   0
9   20                 0         0                   0
10  80                 0        10                   0
   registro_unico_para_analise
1  Sim
2  Sim
3  Sim
4  Sim
5  Sim
6  Sim
7  Sim
8  Sim
9  Sim
10 Sim

[1] 20000    13

 [1] "codigo_municipio"            "municipio"
 [3] "cnes"                        "estabelecimento"
 [5] "natureza_estabelecimento"    "tipo_unidade"
 [7] "tipo_gestao"                 "competencia"
 [9] "leitos_existentes"           "leitos_sus"
[11] "uti_total_existente"         "uti_total_sus"
[13] "registro_unico_para_analise"

spc_tbl_ [20,000 × 13] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ codigo_municipio           : num [1:20000] 3547809 3549904 3549904 3549904 3549904 ...
 $ municipio                  : chr [1:20000] "SANTO ANDRE" "SAO JOSE DOS CAMPOS" "SAO JOSE DOS CAMPOS" "SAO JOSE DOS CAMPOS" ...
 $ cnes                       : chr [1:20000] "0008923" "0009164" "0009539" "0009601" ...
 $ estabelecimento            : chr [1:20000] "CENTRO HOSPITALAR DE SANTO ANDRE DR NEWTON DA COSTA BRANDAO" "UPA SAO FRANCISCO XAVIER" "HOSPITAL MATERNO INFANTIL ANTONINHO DA ROCHA MARMO" "HOSPITAL PIO XII" ...
 $ natureza_estabelecimento   : chr [1:20000] "Hospital público" "Hospital público" "Hospital filantrópico" "Hospital filantrópico" ...
 $ tipo_unidade               : chr [1:20000] "Hospital Geral" "Unidade Mista" "Hospital Geral" "Hospital Geral" ...
 $ tipo_gestao                : chr [1:20000] "Municipal" "Municipal" "Municipal" "Municipal" ...
 $ competencia                : chr [1:20000] "2025-01" "2025-01" "2025-01" "2025-01" ...
 $ leitos_existentes          : num [1:20000] 296 3 54 87 388 174 44 10 20 80 ...
 $ leitos_sus                 : num [1:20000] 296 3 5 72 388 0 44 0 0 0 ...
 $ uti_total_existente        : num [1:20000] 60 0 18 13 72 0 0 0 0 10 ...
 $ uti_total_sus              : num [1:20000] 60 0 0 12 72 0 0 0 0 0 ...
 $ registro_unico_para_analise: chr [1:20000] "Sim" "Sim" "Sim" "Sim" ...
 - attr(*, "spec")=
  .. cols(
  ..   codigo_municipio = col_double(),
  ..   municipio = col_character(),
  ..   cnes = col_character(),
  ..   estabelecimento = col_character(),
  ..   natureza_estabelecimento = col_character(),
  ..   tipo_unidade = col_character(),
  ..   tipo_gestao = col_character(),
  ..   competencia = col_character(),
  ..   leitos_existentes = col_double(),
  ..   leitos_sus = col_double(),
  ..   uti_total_existente = col_double(),
  ..   uti_total_sus = col_double(),
  ..   registro_unico_para_analise = col_character()
  .. )
 - attr(*, "problems")=<pointer: 0x567500f942e0>