<a href="https://colab.research.google.com/github/Izaias02/ANALISES-DE-DADOS/blob/main/2_silver_saude.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ============================================================
# Camada Silver: Download, Limpeza e Tipagem (Saúde via API)
# ============================================================
library(readr)
library(googledrive)

# 1. Mapeando os caminhos da Aula 6 conforme configurado no Bloco 2
pasta_aula    <- "Aula 6 - 31/08/2026"
pasta_origem  <- paste0(pasta_aula, "/0 - Bases de Dados/5 - Saúde")
nome_arquivo  <- "hospitais_leitos_sp_2025_tratado.csv"
caminho_completo_base <- paste0(pasta_origem, "/", nome_arquivo)

cat("🔍 Buscando o arquivo original no Google Drive...\n")

# Localiza o arquivo bruto no Drive usando a API
arquivo_encontrado <- drive_get(path = caminho_completo_base)

# Faz o download limpo para a sessão atual do Colab
drive_download(
  file = arquivo_encontrado,
  path = "/content/hospitais_leitos_sp_2025_tratado.csv",
  overwrite = TRUE
)

# 2. Lendo o arquivo baixado para a memória do R
df_hospitais <- read_csv(
  "/content/hospitais_leitos_sp_2025_tratado.csv",
  locale = locale(encoding = "UTF-8"),
  show_col_types = FALSE
)

# 3. Aplicando a Regra de Purificação da Silver (Removendo Duplicações)
df_hospitais_silver <- df_hospitais[df_hospitais$registro_unico_para_analise == "Sim", ]

# ============================================================
# 4. EXECUÇÃO DO ROTEIRO DE INSPEÇÃO DA ATIVIDADE
# ============================================================

# Visualiza o dataframe tratado.
df_hospitais_silver

# Exibe os primeiros registros limpos.
head(df_hospitais_silver, 10)

# Quantidade de linhas e colunas (Demonstra o antes e depois da limpeza!).
cat("\n📊 Dimensões da Base Silver (Linhas x Colunas):\n")
print(dim(df_hospitais_silver))

# Nome de todas as colunas disponíveis.
cat("\n📋 Nomes das Colunas:\n")
print(names(df_hospitais_silver))

# Estrutura e tipagem das variáveis pós-tratamento.
cat("\n🔬 Estrutura das Variáveis:\n")
str(df_hospitais_silver)

🔍 Buscando o arquivo original no Google Drive...

✔ The input `path` resolved to exactly 1 file.

File downloaded:

• hospitais_leitos_sp_2025_tratado.csv <id: 1d6xwqJV5ZDf8Nt-EdgsuezeUWUvh7juK>

Saved locally as:

• /content/hospitais_leitos_sp_2025_tratado.csv

     codigo_municipio municipio             cnes
1    3547809          SANTO ANDRE           0008923
2    3549904          SAO JOSE DOS CAMPOS   0009164
3    3549904          SAO JOSE DOS CAMPOS   0009539
4    3549904          SAO JOSE DOS CAMPOS   0009601
5    3549904          SAO JOSE DOS CAMPOS   0009628
6    3549904          SAO JOSE DOS CAMPOS   0009636
7    3549904          SAO JOSE DOS CAMPOS   0026417
8    3508504          CACAPAVA              0042021
9    3543402          RIBEIRAO PRETO        0080470
10   3507506          BOTUCATU              0081825
11   3510500          CARAGUATATUBA         0092894
12   3550308          SAO PAULO             0102075
13   3550308          SAO PAULO             0102105
14   3528502          MAIRIPORA             0115509
15   3505708          BARUERI               0127604
16   3538006          PINDAMONHANGABA       0136328
17   3550308          SAO PAULO             0161438
18   3502903          ARACOIABA DA SERRA    0181145
19   3548708          SAO BERNARDO DO CAMPO 0235385
20   3550308          SAO PAULO             0255661
21   3550308          SAO PAULO             0263192
22   3550704          SAO SEBASTIAO         0265187
23   3504107          ATIBAIA               0285641
24   3502101          ANDRADINA             0297607
25   3549904          SAO JOSE DOS CAMPOS   0381454
26   3550308          SAO PAULO             0393290
27   3550308          SAO PAULO             0414808
28   3506003          BAURU                 0419214
29   3511706          CHARQUEADA            0424870
30   3552502          SUZANO                0473561
⋮    ⋮                ⋮                     ⋮
990  3513801          DIADEMA               7261012
991  3533908          OLIMPIA               7264755
992  3550209          SAO MIGUEL ARCANJO    7320175
993  3503208          ARARAQUARA            7352980
994  3550308          SAO PAULO             7357079
995  3554003          TATUI                 7368704
996  3551009          SAO VICENTE           7371349
997  3548708          SAO BERNARDO DO CAMPO 7373465
998  3541406          PRESIDENTE PRUDENTE   7400926
999  3543402          RIBEIRAO PRETO        7420595
1000 3548708          SAO BERNARDO DO CAMPO 7435568
1001 3530607          MOGI DAS CRUZES       7473702
1002 3518701          GUARUJA               7544529
1003 3503208          ARARAQUARA            7564902
1004 3525904          JUNDIAI               7573162
1005 3509007          CAIEIRAS              7580770
1006 3550308          SAO PAULO             7593643
1007 3550308          SAO PAULO             7602227
1008 3521705          ITABERA               7603274
1009 3551504          SERRANA               9773657
1010 3548906          SAO CARLOS            9799176
1011 3509502          CAMPINAS              9806342
1012 3504107          ATIBAIA               9866205
1013 3519709          IBIUNA                9868682
1014 3506003          BAURU                 9915354
1015 3550308          SAO PAULO             9917497
1016 3549904          SAO JOSE DOS CAMPOS   9941487
1017 3550605          SAO ROQUE             9966900
1018 3522505          ITAPEVI               9997032
1019 3534401          OSASCO                0008028
     estabelecimento
1    CENTRO HOSPITALAR DE SANTO ANDRE DR NEWTON DA COSTA BRANDAO
2    UPA SAO FRANCISCO XAVIER
3    HOSPITAL MATERNO INFANTIL ANTONINHO DA ROCHA MARMO
4    HOSPITAL PIO XII
5    HOSPITAL MUNICIPAL DR JOSE DE CARVALHO FLORENCE
6    ASSOCIACAO INSTITUTO CHUI DE PSIQUIATRIA
7    HOSPITAL DE CLINICAS SUL
8    LA SERENITE
9    HOSPITAL FUNDACAO PENTEADO RIBEIRAO PRETO
10   HOSPITAL UNIMED BOTUCATU II
11   HOSPITAL REGIONAL DO LITORAL NORTE
12   HOSPITAL MUNICIPAL DA BELA VISTA SANTA DULCE DOS POBRES
13   HOSPITAL MUNICIPAL BRASILANDIA
14   HOSPITAL DE CLINICAS ANJO GABRIEL
15   HOSPITAL DE RETAGUARDA DO JARDIM PAULISTA
16   UNIDADE MISTA CIDADE NOVA PINDAMONHANGABA
17   HOSPITAL MUNICIPAL GUARAPIRANGA
18   HOSPITAL NOVA REABILITACAO
19   CLINICA TERAPEUTICA SONHO DE VIDA
20   IMPAR SERVICOS HOSPITALARES FILIAL SANTA PAULA
21   HOSPITAL SANCTA MAGGIORE DUBAI
22   HOSPITAL DE CLINICAS DE SAO SEBASTIAO COSTA SUL
23   GRUPO ERIMUS
24   OCULARE ANDRADINA
25   HOSPITAL ORTO SERVICOS MEDICOS E CIRURGICOS
26   HOSPITAL E PRONTO ATENDIMENTO SANCTA MAGGIORE RUSSIA
27   CRIA CASA DE PARTO
28   REDE ONE CARE
29   HOSPITAL TERAPEUTICO RENOVARE
30   HOSPITAL SAINT NICHOLAS MEDICAL
⋮    ⋮
990  INNOVA HOSPITAIS ASSOCIADOS LTDA
991  PRONTO ATENDIMENTO UNIMED DE OLIMPIA
992  HOSPITAL SAO MIGUEL ARCANJO
993  DUO DAY HOSPITAL
994  HOSPITAL SANCTA MAGGIORE
995  HOSPITAL UNIMED TATUI JOSE FCO M DE ALMEIDA DR KIKO
996  HOSPITAL DR OLAVO HORNEAUX DE MOURA SAO VICENTE
997  HOSPITAL DE CLINICAS MUNICIPAL
998  FUNDACAO HOSPITAL REGIONAL DO CANCER
999  HOSPITAL MUNICIPAL FRANCISCO DE ASSIS RIBEIRAO PRETO
1000 HOSPITAL E PRONTO ATENDIMENTO SANCTA MAGGIORE
1001 HOSP MUN DE MOGI DAS CRUZES PREF WALDEMAR COSTA FILHO
1002 INST DE INFECT EMILIO RIBAS II BAIXADA SANTISTA
1003 HOSPITAL ARARAQUARA
1004 HOSPITAL REGIONAL DE JUNDIAI
1005 HOSPITAL ESTADUAL DE CAIEIRAS
1006 COMPLEXO HOSPITALAR SANTO EXPEDITO
1007 HOSPITAL SAINT PETER
1008 HOSPITAL MUNICIPAL SAO JOSE
1009 HOSPITAL ESTADUAL DE SERRANA
1010 NORDEN HOSPITAL
1011 HOSPITAL SAMARITANO UNIDADE II
1012 HOSPITAL PSIQUIATRICO ESTRELA DO AMANHECER
1013 INSTITUTO LEONARDO RUSSO
1014 HOSPITAL BAURU
1015 PRIME HOUSE CENTRO TERAPEUTICO
1016 HOSPITAL ROYAL CARE SAO JOSE DOS CAMPOS
1017 HOSPITAL SAO FRANCISCO
1018 HOSPITAL YES
1019 HOSPITAL MUNICIPAL ANTONIO GIGLIO
     natureza_estabelecimento tipo_unidade                 tipo_gestao
1    Hospital público         Hospital Geral               Municipal
2    Hospital público         Unidade Mista                Municipal
3    Hospital filantrópico    Hospital Geral               Municipal
4    Hospital filantrópico    Hospital Geral               Municipal
5    Hospital público         Hospital Geral               Municipal
6    Hospital filantrópico    Hospital Especializado       Municipal
7    Hospital público         Hospital Geral               Municipal
8    Hospital privado         Hospital Especializado       Municipal
9    Hospital filantrópico    Hospital Geral               Municipal
10   Hospital privado         Hospital Geral               Municipal
11   Hospital público         Hospital Geral               Estadual
12   Hospital público         Hospital Geral               Municipal
13   Hospital público         Hospital Geral               Municipal
14   Hospital público         Hospital Geral               Municipal
15   Hospital público         Hospital Geral               Municipal
16   Hospital público         Unidade Mista                Municipal
17   Hospital público         Hospital Geral               Municipal
18   Hospital privado         Hospital Especializado       Municipal
19   Hospital privado         Hospital Especializado       Municipal
20   Hospital privado         Hospital Geral               Municipal
21   Hospital privado         Hospital Geral               Municipal
22   Hospital público         Hospital Geral               Municipal
23   Hospital privado         Hospital Especializado       Municipal
24   Hospital privado         Hospital Especializado       Municipal
25   Hospital privado         Pronto Socorro Especializado Municipal
26   Hospital privado         Hospital Geral               Municipal
27   Hospital privado         Hospital Geral               Municipal
28   Hospital privado         Hospital Geral               Municipal
29   Hospital privado         Hospital Geral               Municipal
30   Hospital privado         Hospital Geral               Municipal
⋮    ⋮                        ⋮                            ⋮
990  Hospital privado         Hospital Geral               Municipal
991  Hospital privado         Pronto Socorro Geral         Municipal
992  Hospital filantrópico    Hospital Geral               Municipal
993  Hospital privado         Hospital Especializado       Municipal
994  Hospital privado         Hospital Geral               Municipal
995  Hospital privado         Hospital Geral               Municipal
996  Hospital público         Hospital Geral               Municipal
997  Hospital público         Hospital Geral               Municipal
998  Hospital filantrópico    Hospital Especializado       Estadual
999  Hospital público         Hospital Geral               Municipal
1000 Hospital privado         Hospital Geral               Municipal
1001 Hospital público         Hospital Geral               Municipal
1002 Hospital público         Hospital Geral               Estadual
1003 Hospital privado         Hospital Geral               Municipal
1004 Hospital público         Hospital Geral               Estadual
1005 Hospital público         Hospital Geral               Estadual
1006 Hospital privado         Hospital Geral               Municipal
1007 Hospital privado         Hospital Geral               Municipal
1008 Hospital público         Hospital Geral               Municipal
1009 Hospital público         Hospital Geral               Estadual
1010 Hospital privado         Hospital Geral               Municipal
1011 Hospital filantrópico    Hospital Geral               Municipal
1012 Hospital privado         Hospital Especializado       Municipal
1013 Hospital privado         Hospital Especializado       Municipal
1014 Hospital privado         Hospital Geral               Municipal
1015 Hospital privado         Hospital Especializado       Municipal
1016 Hospital privado         Hospital Geral               Municipal
1017 Hospital privado         Hospital Geral               Municipal
1018 Hospital privado         Hospital Geral               Municipal
1019 Hospital público         Hospital Geral               Municipal
     competencia leitos_existentes leitos_sus uti_total_existente uti_total_sus
1    2025-01     296               296        60                  60
2    2025-01       3                 3         0                   0
3    2025-01      54                 5        18                   0
4    2025-01      87                72        13                  12
5    2025-01     388               388        72                  72
6    2025-01     174                 0         0                   0
7    2025-01      44                44         0                   0
8    2025-01      10                 0         0                   0
9    2025-01      20                 0         0                   0
10   2025-01      80                 0        10                   0
11   2025-01     201               201        40                  40
12   2025-01     113                93        20                   0
13   2025-01     323               283        70                  30
14   2025-01      35                35         0                   0
15   2025-01      61                61         0                   0
16   2025-01       2                 2         0                   0
17   2025-01     216               186        30                   0
18   2025-01      41                 0         0                   0
19   2025-01      32                 0         0                   0
20   2025-01     199                 0        50                   0
21   2025-01     171                 0        37                   0
22   2025-01      29                29         0                   0
23   2025-01      29                 0         0                   0
24   2025-01       1                 0         0                   0
25   2025-01       1                 0         0                   0
26   2025-01      43                 0         0                   0
27   2025-01       7                 0         0                   0
28   2025-01       3                 0         0                   0
29   2025-01       2                 0         0                   0
30   2025-01     111                 0        31                   0
⋮    ⋮           ⋮                 ⋮          ⋮                   ⋮
990  2025-01      60                 0        21                   0
991  2025-01       1                 0         0                   0
992  2025-01      79                79         0                   0
993  2025-01       9                 0         0                   0
994  2025-01     101                 0        29                   0
995  2025-01      59                 0        14                   0
996  2025-01      59                59         0                   0
997  2025-01     266               266        60                  60
998  2025-01     113                72        10                  10
999  2025-01      31                31         0                   0
1000 2025-01      10                 0         0                   0
1001 2025-01      69                69        10                  10
1002 2025-01      45                45        13                  13
1003 2025-01      35                 0        10                   0
1004 2025-01     140               136        20                  16
1005 2025-01      54                54         6                   6
1006 2025-01     171                 0        20                   0
1007 2025-01      55                 0         4                   0
1008 2025-01      19                19         0                   0
1009 2025-01      82                82        10                  10
1010 2025-01      17                 0         0                   0
1011 2025-01      10                 0         0                   0
1012 2025-01      40                 0         0                   0
1013 2025-01      27                 0         0                   0
1014 2025-01      55                 0        13                   0
1015 2025-01      36                 0         0                   0
1016 2025-01      46                 0         0                   0
1017 2025-01      56                 0         8                   0
1018 2025-01     120                 0        40                   0
1019 2025-02     225               201        28                  20
     registro_unico_para_analise
1    Sim
2    Sim
3    Sim
4    Sim
5    Sim
6    Sim
7    Sim
8    Sim
9    Sim
10   Sim
11   Sim
12   Sim
13   Sim
14   Sim
15   Sim
16   Sim
17   Sim
18   Sim
19   Sim
20   Sim
21   Sim
22   Sim
23   Sim
24   Sim
25   Sim
26   Sim
27   Sim
28   Sim
29   Sim
30   Sim
⋮    ⋮
990  Sim
991  Sim
992  Sim
993  Sim
994  Sim
995  Sim
996  Sim
997  Sim
998  Sim
999  Sim
1000 Sim
1001 Sim
1002 Sim
1003 Sim
1004 Sim
1005 Sim
1006 Sim
1007 Sim
1008 Sim
1009 Sim
1010 Sim
1011 Sim
1012 Sim
1013 Sim
1014 Sim
1015 Sim
1016 Sim
1017 Sim
1018 Sim
1019 Sim

   codigo_municipio municipio           cnes
1  3547809          SANTO ANDRE         0008923
2  3549904          SAO JOSE DOS CAMPOS 0009164
3  3549904          SAO JOSE DOS CAMPOS 0009539
4  3549904          SAO JOSE DOS CAMPOS 0009601
5  3549904          SAO JOSE DOS CAMPOS 0009628
6  3549904          SAO JOSE DOS CAMPOS 0009636
7  3549904          SAO JOSE DOS CAMPOS 0026417
8  3508504          CACAPAVA            0042021
9  3543402          RIBEIRAO PRETO      0080470
10 3507506          BOTUCATU            0081825
   estabelecimento
1  CENTRO HOSPITALAR DE SANTO ANDRE DR NEWTON DA COSTA BRANDAO
2  UPA SAO FRANCISCO XAVIER
3  HOSPITAL MATERNO INFANTIL ANTONINHO DA ROCHA MARMO
4  HOSPITAL PIO XII
5  HOSPITAL MUNICIPAL DR JOSE DE CARVALHO FLORENCE
6  ASSOCIACAO INSTITUTO CHUI DE PSIQUIATRIA
7  HOSPITAL DE CLINICAS SUL
8  LA SERENITE
9  HOSPITAL FUNDACAO PENTEADO RIBEIRAO PRETO
10 HOSPITAL UNIMED BOTUCATU II
   natureza_estabelecimento tipo_unidade           tipo_gestao competencia
1  Hospital público         Hospital Geral         Municipal   2025-01
2  Hospital público         Unidade Mista          Municipal   2025-01
3  Hospital filantrópico    Hospital Geral         Municipal   2025-01
4  Hospital filantrópico    Hospital Geral         Municipal   2025-01
5  Hospital público         Hospital Geral         Municipal   2025-01
6  Hospital filantrópico    Hospital Especializado Municipal   2025-01
7  Hospital público         Hospital Geral         Municipal   2025-01
8  Hospital privado         Hospital Especializado Municipal   2025-01
9  Hospital filantrópico    Hospital Geral         Municipal   2025-01
10 Hospital privado         Hospital Geral         Municipal   2025-01
   leitos_existentes leitos_sus uti_total_existente uti_total_sus
1  296               296        60                  60
2    3                 3         0                   0
3   54                 5        18                   0
4   87                72        13                  12
5  388               388        72                  72
6  174                 0         0                   0
7   44                44         0                   0
8   10                 0         0                   0
9   20                 0         0                   0
10  80                 0        10                   0
   registro_unico_para_analise
1  Sim
2  Sim
3  Sim
4  Sim
5  Sim
6  Sim
7  Sim
8  Sim
9  Sim
10 Sim

📊 Dimensões da Base Silver (Linhas x Colunas):
[1] 1019   13

📋 Nomes das Colunas:
 [1] "codigo_municipio"            "municipio"
 [3] "cnes"                        "estabelecimento"
 [5] "natureza_estabelecimento"    "tipo_unidade"
 [7] "tipo_gestao"                 "competencia"
 [9] "leitos_existentes"           "leitos_sus"
[11] "uti_total_existente"         "uti_total_sus"
[13] "registro_unico_para_analise"

🔬 Estrutura das Variáveis:
tibble [1,019 × 13] (S3: tbl_df/tbl/data.frame)
 $ codigo_municipio           : num [1:1019] 3547809 3549904 3549904 3549904 3549904 ...
 $ municipio                  : chr [1:1019] "SANTO ANDRE" "SAO JOSE DOS CAMPOS" "SAO JOSE DOS CAMPOS" "SAO JOSE DOS CAMPOS" ...
 $ cnes                       : chr [1:1019] "0008923" "0009164" "0009539" "0009601" ...
 $ estabelecimento            : chr [1:1019] "CENTRO HOSPITALAR DE SANTO ANDRE DR NEWTON DA COSTA BRANDAO" "UPA SAO FRANCISCO XAVIER" "HOSPITAL MATERNO INFANTIL ANTONINHO DA ROCHA MARMO" "HOSPITAL PIO XII" ...
 $ natureza_estabelecimento   : chr [1:1019] "Hospital público" "Hospital público" "Hospital filantrópico" "Hospital filantrópico" ...
 $ tipo_unidade               : chr [1:1019] "Hospital Geral" "Unidade Mista" "Hospital Geral" "Hospital Geral" ...
 $ tipo_gestao                : chr [1:1019] "Municipal" "Municipal" "Municipal" "Municipal" ...
 $ competencia                : chr [1:1019] "2025-01" "2025-01" "2025-01" "2025-01" ...
 $ leitos_existentes          : num [1:1019] 296 3 54 87 388 174 44 10 20 80 ...
 $ leitos_sus                 : num [1:1019] 296 3 5 72 388 0 44 0 0 0 ...
 $ uti_total_existente        : num [1:1019] 60 0 18 13 72 0 0 0 0 10 ...
 $ uti_total_sus              : num [1:1019] 60 0 0 12 72 0 0 0 0 0 ...
 $ registro_unico_para_analise: chr [1:1019] "Sim" "Sim" "Sim" "Sim" ...

In [ ]:
# ============================================================
# 4. FILTRAGEM DE DUPLICIDADES E HIGIENIZAÇÃO (SILVER) - VERSÃO BASE
# ============================================================

# Filtragem direta usando colchetes [linhas, colunas] - Método padrão e estável no R
df_hospitais_silver <- df_hospitais[df_hospitais$registro_unico_para_analise == "Sim", ]

# Remove possíveis linhas que venham completamente vazias (NA) por segurança
df_hospitais_silver <- df_hospitais_silver[!is.na(df_hospitais_silver$registro_unico_para_analise), ]

# ============================================================
# 5. DIAGNÓSTICO DO ANTES E DEPOIS (ROTEIRO OFICIAL)
# ============================================================

# Visualiza os primeiros registros filtrados
head(df_hospitais_silver, 10)

# Quantidade de linhas e colunas pós-limpeza (Compare com o anterior!)
cat("\n📊 Dimensões da Base após a limpeza na Camada Silver:\n")
print(dim(df_hospitais_silver))

# Nome de todas as colunas que restaram e estão higienizadas
cat("\n📋 Colunas prontas para o SBC:\n")
print(names(df_hospitais_silver))

# Estrutura final e conferência de tipos das variáveis
cat("\n🔬 Estrutura técnica pós-tratamento:\n")
str(df_hospitais_silver)

   codigo_municipio municipio           cnes
1  3547809          SANTO ANDRE         0008923
2  3549904          SAO JOSE DOS CAMPOS 0009164
3  3549904          SAO JOSE DOS CAMPOS 0009539
4  3549904          SAO JOSE DOS CAMPOS 0009601
5  3549904          SAO JOSE DOS CAMPOS 0009628
6  3549904          SAO JOSE DOS CAMPOS 0009636
7  3549904          SAO JOSE DOS CAMPOS 0026417
8  3508504          CACAPAVA            0042021
9  3543402          RIBEIRAO PRETO      0080470
10 3507506          BOTUCATU            0081825
   estabelecimento
1  CENTRO HOSPITALAR DE SANTO ANDRE DR NEWTON DA COSTA BRANDAO
2  UPA SAO FRANCISCO XAVIER
3  HOSPITAL MATERNO INFANTIL ANTONINHO DA ROCHA MARMO
4  HOSPITAL PIO XII
5  HOSPITAL MUNICIPAL DR JOSE DE CARVALHO FLORENCE
6  ASSOCIACAO INSTITUTO CHUI DE PSIQUIATRIA
7  HOSPITAL DE CLINICAS SUL
8  LA SERENITE
9  HOSPITAL FUNDACAO PENTEADO RIBEIRAO PRETO
10 HOSPITAL UNIMED BOTUCATU II
   natureza_estabelecimento tipo_unidade           tipo_gestao competencia
1  Hospital público         Hospital Geral         Municipal   2025-01
2  Hospital público         Unidade Mista          Municipal   2025-01
3  Hospital filantrópico    Hospital Geral         Municipal   2025-01
4  Hospital filantrópico    Hospital Geral         Municipal   2025-01
5  Hospital público         Hospital Geral         Municipal   2025-01
6  Hospital filantrópico    Hospital Especializado Municipal   2025-01
7  Hospital público         Hospital Geral         Municipal   2025-01
8  Hospital privado         Hospital Especializado Municipal   2025-01
9  Hospital filantrópico    Hospital Geral         Municipal   2025-01
10 Hospital privado         Hospital Geral         Municipal   2025-01
   leitos_existentes leitos_sus uti_total_existente uti_total_sus
1  296               296        60                  60
2    3                 3         0                   0
3   54                 5        18                   0
4   87                72        13                  12
5  388               388        72                  72
6  174                 0         0                   0
7   44                44         0                   0
8   10                 0         0                   0
9   20                 0         0                   0
10  80                 0        10                   0
   registro_unico_para_analise
1  Sim
2  Sim
3  Sim
4  Sim
5  Sim
6  Sim
7  Sim
8  Sim
9  Sim
10 Sim

📊 Dimensões da Base após a limpeza na Camada Silver:
[1] 1019   13

📋 Colunas prontas para o SBC:
 [1] "codigo_municipio"            "municipio"
 [3] "cnes"                        "estabelecimento"
 [5] "natureza_estabelecimento"    "tipo_unidade"
 [7] "tipo_gestao"                 "competencia"
 [9] "leitos_existentes"           "leitos_sus"
[11] "uti_total_existente"         "uti_total_sus"
[13] "registro_unico_para_analise"

🔬 Estrutura técnica pós-tratamento:
tibble [1,019 × 13] (S3: tbl_df/tbl/data.frame)
 $ codigo_municipio           : num [1:1019] 3547809 3549904 3549904 3549904 3549904 ...
 $ municipio                  : chr [1:1019] "SANTO ANDRE" "SAO JOSE DOS CAMPOS" "SAO JOSE DOS CAMPOS" "SAO JOSE DOS CAMPOS" ...
 $ cnes                       : chr [1:1019] "0008923" "0009164" "0009539" "0009601" ...
 $ estabelecimento            : chr [1:1019] "CENTRO HOSPITALAR DE SANTO ANDRE DR NEWTON DA COSTA BRANDAO" "UPA SAO FRANCISCO XAVIER" "HOSPITAL MATERNO INFANTIL ANTONINHO DA ROCHA MARMO" "HOSPITAL PIO XII" ...
 $ natureza_estabelecimento   : chr [1:1019] "Hospital público" "Hospital público" "Hospital filantrópico" "Hospital filantrópico" ...
 $ tipo_unidade               : chr [1:1019] "Hospital Geral" "Unidade Mista" "Hospital Geral" "Hospital Geral" ...
 $ tipo_gestao                : chr [1:1019] "Municipal" "Municipal" "Municipal" "Municipal" ...
 $ competencia                : chr [1:1019] "2025-01" "2025-01" "2025-01" "2025-01" ...
 $ leitos_existentes          : num [1:1019] 296 3 54 87 388 174 44 10 20 80 ...
 $ leitos_sus                 : num [1:1019] 296 3 5 72 388 0 44 0 0 0 ...
 $ uti_total_existente        : num [1:1019] 60 0 18 13 72 0 0 0 0 10 ...
 $ uti_total_sus              : num [1:1019] 60 0 0 12 72 0 0 0 0 0 ...
 $ registro_unico_para_analise: chr [1:1019] "Sim" "Sim" "Sim" "Sim" ...

In [ ]:
# ============================================================
# 6. EXPORTAÇÃO DA CAMADA SILVER (MÉTODO ID DIRETO - INFALÍVEL)
# ============================================================
library(googledrive)

cat("🔍 Buscando identificador único da pasta '2-silver' na nuvem...\n")

# Faz uma busca global no Drive pelo nome da pasta para capturar o ID correto de rede
busca_pasta_silver <- drive_find(pattern = "2-silver", type = "folder", n_max = 1)

if (nrow(busca_pasta_silver) > 0) {
  cat("✅ Pasta encontrada! ID de Rede:", busca_pasta_silver$id[1], "\n")

  # Salva o arquivo limpo temporariamente no espaço do Colab (/content)
  write.csv(df_hospitais_silver, "/content/hospitais_leitos_sp_2025_silver.csv", row.names = FALSE)

  cat("📤 Iniciando upload do arquivo tratado utilizando o ID seguro...\n")

  # Faz o upload usando a linha da tabela localizada pela busca, ignorando caminhos de texto
  drive_upload(
    media = "/content/hospitais_leitos_sp_2025_silver.csv",
    path = as_id(busca_pasta_silver$id[1]),
    name = "hospitais_leitos_sp_2025_silver.csv",
    overwrite = TRUE
  )

  cat("🎉 SUCESSO ABSOLUTO, IZAIAS! O R quebrou o bloqueio e salvou a Camada Silver no seu Drive!\n")

} else {
  cat("❌ ERRO: A pasta '2-silver' não foi localizada na busca global.\n")
  cat("👉 Como plano de emergência, execute esta linha para salvar o arquivo na tela local do seu Colab:\n")
  write.csv(df_hospitais_silver, "/content/hospitais_leitos_sp_2025_silver.csv", row.names = FALSE)
  cat("O arquivo 'hospitais_leitos_sp_2025_silver.csv' aparecerá na barra da esquerda para baixar no seu PC!\n")
}

🔍 Buscando identificador único da pasta '2-silver' na nuvem...
✅ Pasta encontrada! ID de Rede: 1RmeRyuSKwUebw5losuaQvcVKvV3rbjSf
📤 Iniciando upload do arquivo tratado utilizando o ID seguro...

Local file:

• /content/hospitais_leitos_sp_2025_silver.csv

Uploaded into Drive file:

• hospitais_leitos_sp_2025_silver.csv <id: 1H4SVdfQPVtgVlUjgWruSeD1IeYQ6HYnJ>

With MIME type:

• text/csv

🎉 SUCESSO ABSOLUTO, IZAIAS! O R quebrou o bloqueio e salvou a Camada Silver no seu Drive!